name: cmed_lib_flutter
publish_to: 'none'
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  #flutter_rapid
  flutter_rapid:
    git:
      url: https://github.com/banglafighter/flutter_rapid.git
      ref: dev
      path: flutter_rapid

  audioplayers: ^6.1.0
  themed: ^7.0.0
  flutter_blue_plus: ^1.35.3
  group_radio_button: ^1.2.0
  dropdown_button2: ^2.3.9
  flutter_form_builder: 10.0.1
  package_info_plus: ^8.1.0
  device_info_plus: ^11.1.0
  form_builder_validators: 11.2.0
  intl: ^0.20.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  marquee: ^2.3.0
  dio: ^5.7.0
  age_calculator: ^1.0.0
  date_format: ^2.0.6
  flutter_cupertino_date_picker_fork: ^1.0.7
  fluttertoast: ^9.0.0
  image_picker: ^1.2.1
  flutter_file_dialog: ^3.0.2
  file_picker: 8.1.0
  flutter_image_compress: ^2.4.0
  permission_handler: ^11.3.1
  photo_view: ^0.14.0
  google_fonts:
  fl_chart: 1.0.0
  #flutter_downloader
  flutter_downloader: 1.12.0
  chucker_flutter:
    git:
      url: https://gitlab.com/ToufiqurTushar/chucker-flutter.git
      ref: main
  #plugin
  endometriosis_lib_flutter:
    git:
      url: https://gitlab.com/cmed-bd/endometriosis-lib-flutter.git
      #url: git@gitlab.com:cmed-bd/endometriosis-lib-flutter.git
      ref: main
  #  alzheimer_lib_flutter:
  #    git:
  #      url: https://gitlab.com/cmed-bd/alzheimer-lib-flutter.git
  #      #url: git@gitlab.com:cmed-bd/alzheimer-lib-flutter.git
  #      ref: dev

  #device plugin
  cmed_bp_device_lib:
    git:
      url: https://gitlab.com/cmed-bd/cmed_bp_device_lib.git
      #url: git@gitlab.com:cmed-bd/cmed_bp_device_lib
      ref: main
  cmed_spo2_devices_lib:
    git:
      url: https://gitlab.com/cmed-bd/spo2-lib-flutter.git
      #url: git@gitlab.com:cmed-bd/spo2-lib-flutter.git
      ref: main
  cmed_bmi_devices_lib:
    git:
      url: https://gitlab.com/cmed-bd/bmi-lib-flutter.git
      #url: git@gitlab.com:cmed-bd/bmi-lib-flutter.git
      ref: main
  cmed_blood_glucose_devices_lib:
    git:
      url: https://gitlab.com/cmed-bd/glucose-lib-flutter.git
      #url: git@gitlab.com:cmed-bd/glucose-lib-flutter.git
      ref: main
  cmed_ecg_devices_lib:
    git:
      url: https://gitlab.com/cmed-bd/ecg-lib-flutter.git
      #url: git@gitlab.com:cmed-bd/ecg-lib-flutter.git
      ref: susastho_lite_ecg
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.cmedhealth.flutterlib.cmed_lib_flutter
        pluginClass: CmedLibFlutterPlugin
      ios:
        pluginClass: CmedLibFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
